# Generated by Django 4.0.5 on 2022-07-09 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pedidos')),
                ('estado', models.IntegerField(verbose_name='Estado_Pedido')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_pedidos', to='core.carrito')),
            ],
        ),
    ]
