# Generated by Django 4.0.5 on 2022-07-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to='core/templates/core/img/productos'),
        ),
    ]
